import wasm from "sketches/random_rhombus_tilings/wasm/rhombus_randomiser.wasm"
import type {instantiate} from "./wasm/rhombus_randomiser"

type Exports = ReturnType<typeof instantiate> extends Promise<infer X>? X: never

// this file exists because default autogenerated bindings suck, for two reasons:
// 1. no interop with Parcel. it is expected to know URL of wasm binary ahead of time, which is not the case for us
// 2. no support for .instantiateStreaming
export const getWasmRhombusRandomiser = async(): Promise<Exports> => {
	const {instance} = await WebAssembly.instantiateStreaming(fetch(wasm))
	return instance.exports as Exports
}